import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../Components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ECR Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />
      
    <div className="latest">
      <h2>Latest:</h2>
    </div>



    </div>
  )
}
